- hosts: all
  tasks:
    - name: Update all packages to the latest version
      apt:
         name: "*"
         state: latest
         force_apt_get: yes
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      become: yes
    - name: Install Apache+PHP
      apt:
         name: "{{ packages }}"
      vars:
         packages:
         - apache2
         - libapache2-mod-php
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
      become: yes
    - name: Update all packages to the latest version
      yum:
         name: '*'
         state: latest
         exclude: kernel*
      when: ansible_distribution == "CentOS"
      become: yes
    - name: Install Apache+PHP
      yum:
         name: "{{ packages }}"
      vars:
         packages:
         - httpd
         - php
         - php-mysql
      when: ansible_distribution == "CentOS"
